# Generated by Django 5.2.7 on 2025-10-28 22:48

import django.db.models.deletion
import perfil.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('bio', models.TextField(blank=True, verbose_name='Biografia')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=perfil.validators.upload_path_avatar, validators=[perfil.validators.validar_tamanho_avatar, perfil.validators.validar_tipo_avatar], verbose_name='Avatar')),
                ('telefone', models.CharField(blank=True, max_length=15, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('email_institucional', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email Institucional')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
    ]
