# Generated by Django 5.2.7 on 2025-10-28 22:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enunciado', models.TextField()),
                ('complemento', models.ImageField(blank=True, null=True, upload_to='questoes/')),
                ('alternativa_a', models.CharField(blank=True, max_length=500, null=True)),
                ('alternativa_b', models.CharField(blank=True, max_length=500, null=True)),
                ('alternativa_c', models.CharField(blank=True, max_length=500, null=True)),
                ('alternativa_d', models.CharField(blank=True, max_length=500, null=True)),
                ('alternativa_e', models.CharField(blank=True, max_length=500, null=True)),
                ('resposta_correta', models.CharField(choices=[('A', 'Alternativa A'), ('B', 'Alternativa B'), ('C', 'Alternativa C'), ('D', 'Alternativa D'), ('E', 'Alternativa E')], max_length=1)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes_criadas', to='perfil.perfilusuario')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='hometask.materia')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
